python
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_info(object):
    def setupUi(self, Dialog_info):
        Dialog_info.setStyleSheet("background-color: rgb(189,215,238)")
        Dialog_info.setObjectName("Dialog_info")
        Dialog_info.resize(394, 500)
        self.button_confirm = QtWidgets.QPushButton(Dialog_info)
        self.button_confirm.setGeometry(QtCore.QRect(260, 452, 112, 34))
        self.button_confirm.setObjectName("button_confirm")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog_info)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 50, 331, 400))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)

        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_9)

        self.line_id = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_id.setObjectName("line_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_id)
        self.line_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_name.setObjectName("line_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_name)
        self.line_sex = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_sex.setObjectName("line_sex")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_sex)
        self.line_address = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_address.setObjectName("line_address")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_address)

        self.line_passwords = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_passwords.setObjectName("line_passwords")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.line_passwords)
        self.line_age = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_age.setObjectName("line_name")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.line_age)
        self.line_race = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_race.setObjectName("line_race")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.line_race)
        self.line_emotion = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_emotion.setObjectName("line_emotion")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.line_emotion)
        self.line_check = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_check.setObjectName("line_check")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.line_check)

        self.retranslateUi(Dialog_info)
        QtCore.QMetaObject.connectSlotsByName(Dialog_info)

        Dialog_info.setTabOrder(self.line_id, self.line_name)
        Dialog_info.setTabOrder(self.line_name, self.line_sex)
        Dialog_info.setTabOrder(self.line_sex, self.line_address)

        Dialog_info.setTabOrder(self.line_address, self.line_passwords)
        Dialog_info.setTabOrder(self.line_passwords, self.line_age)
        Dialog_info.setTabOrder(self.line_age, self.line_race)
        Dialog_info.setTabOrder(self.line_race, self.line_emotion)
        Dialog_info.setTabOrder(self.line_emotion, self.line_check)

    def retranslateUi(self, Dialog_info):
        _translate = QtCore.QCoreApplication.translate
        Dialog_info.setWindowTitle(_translate("Dialog_info", "Information Details"))
        self.button_confirm.setText(_translate("Dialog_info", "Determine"))
        self.label.setText(_translate("Dialog_input", "Name："))
        self.label_2.setText(_translate("Dialog_input", "Student ID*："))
        self.label_3.setText(_translate("Dialog_input", "Gender："))
        self.label_4.setText(_translate("Dialog_input", "Native place："))
        self.label_5.setText(_translate("Dialog_input", "Password："))
        self.label_6.setText(_translate("Dialog_input", "Age："))
        self.label_7.setText(_translate("Dialog_input", "Race："))
        self.label_8.setText(_translate("Dialog_input", "Time："))
        self.label_9.setText(_translate("Dialog_input", "Sign status："))
